use_frameworks!

platform :ios, '8.0'

target 'LSSCharts_Example' do
  pod 'LSSCharts', :path => '../'

  target 'LSSCharts_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
