use_frameworks!

platform :ios, '10.0'
source 'https://github.com/LuShanshan633/LSSSpecs.git'
target 'LSSCharts_Example' do
  pod 'LSSCharts', :path => '../'
  target 'LSSCharts_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
